apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: greg-artist
  description: Greg artis website
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: artist-engagement-portal
